plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.moderntvlauncher'

    compileSdk 35

    defaultConfig {
        applicationId "com.example.moderntvlauncher"

        minSdk 23
        targetSdk 28

        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
